# Generated by Django 5.2.8 on 2025-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='Enter a nickname (optional)', max_length=30),
        ),
    ]
