# Generated by Django 5.2.8 on 2025-12-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Write a short bio about yourself.', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, help_text='What should we call you?', max_length=30),
        ),
    ]
